image: gitlab.s059224.slurm.io:5050/s059224/application/
imageTag: master.1
imagePullSecret: cicd-gitlab-registry


replicas: 2


resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 256Mi

service:
  app_port: 5000
  port: 80

ingress:
  host: flask.s059224.edu.slurm.io
